### ISSUE TITLE
Fixing the small issues - TODO

### ISSUE THREAD

**Issue by JasonP01** [Yrueii/Yrueii.github.io#1]
- [ ] Make left hamburger menu disappear when clicked

- [ ] Hide left scrollbar when menu is not open

- [ ] Find any spelling errors and/or grammar issues (unlikely to find any)

Will add more when i start probably

**Comment by Yrueii** [comment]
pog, thanks in advanced for your contribution
